package com.bloodnet.api.model;

public class TblAcid {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_acid.acid
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    private String acid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_acid.user_id
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_acid.create_app
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    private String createApp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_acid.create_user
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_acid.create_dt
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    private String createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_acid.update_app
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    private String updateApp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_acid.update_user
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_acid.update_dt
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    private String updateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_acid.acid
     *
     * @return the value of tbl_acid.acid
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public String getAcid() {
        return acid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_acid.acid
     *
     * @param acid the value for tbl_acid.acid
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public void setAcid(String acid) {
        this.acid = acid == null ? null : acid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_acid.user_id
     *
     * @return the value of tbl_acid.user_id
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_acid.user_id
     *
     * @param userId the value for tbl_acid.user_id
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_acid.create_app
     *
     * @return the value of tbl_acid.create_app
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public String getCreateApp() {
        return createApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_acid.create_app
     *
     * @param createApp the value for tbl_acid.create_app
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public void setCreateApp(String createApp) {
        this.createApp = createApp == null ? null : createApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_acid.create_user
     *
     * @return the value of tbl_acid.create_user
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_acid.create_user
     *
     * @param createUser the value for tbl_acid.create_user
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_acid.create_dt
     *
     * @return the value of tbl_acid.create_dt
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public String getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_acid.create_dt
     *
     * @param createDt the value for tbl_acid.create_dt
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public void setCreateDt(String createDt) {
        this.createDt = createDt == null ? null : createDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_acid.update_app
     *
     * @return the value of tbl_acid.update_app
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public String getUpdateApp() {
        return updateApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_acid.update_app
     *
     * @param updateApp the value for tbl_acid.update_app
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public void setUpdateApp(String updateApp) {
        this.updateApp = updateApp == null ? null : updateApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_acid.update_user
     *
     * @return the value of tbl_acid.update_user
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_acid.update_user
     *
     * @param updateUser the value for tbl_acid.update_user
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_acid.update_dt
     *
     * @return the value of tbl_acid.update_dt
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_acid.update_dt
     *
     * @param updateDt the value for tbl_acid.update_dt
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt == null ? null : updateDt.trim();
    }
}