package com.bloodnet.api.model;

public class TblCouple {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_couple.couple_id
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    private String coupleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_couple.wife_profile_id
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    private String wifeProfileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_couple.husband_profile_id
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    private String husbandProfileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_couple.registrar_id
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    private String registrarId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_couple.delflg
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    private Boolean delflg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_couple.create_dt
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    private String createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_couple.update_dt
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    private String updateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_couple.couple_id
     *
     * @return the value of tbl_couple.couple_id
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public String getCoupleId() {
        return coupleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_couple.couple_id
     *
     * @param coupleId the value for tbl_couple.couple_id
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public void setCoupleId(String coupleId) {
        this.coupleId = coupleId == null ? null : coupleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_couple.wife_profile_id
     *
     * @return the value of tbl_couple.wife_profile_id
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public String getWifeProfileId() {
        return wifeProfileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_couple.wife_profile_id
     *
     * @param wifeProfileId the value for tbl_couple.wife_profile_id
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public void setWifeProfileId(String wifeProfileId) {
        this.wifeProfileId = wifeProfileId == null ? null : wifeProfileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_couple.husband_profile_id
     *
     * @return the value of tbl_couple.husband_profile_id
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public String getHusbandProfileId() {
        return husbandProfileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_couple.husband_profile_id
     *
     * @param husbandProfileId the value for tbl_couple.husband_profile_id
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public void setHusbandProfileId(String husbandProfileId) {
        this.husbandProfileId = husbandProfileId == null ? null : husbandProfileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_couple.registrar_id
     *
     * @return the value of tbl_couple.registrar_id
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public String getRegistrarId() {
        return registrarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_couple.registrar_id
     *
     * @param registrarId the value for tbl_couple.registrar_id
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public void setRegistrarId(String registrarId) {
        this.registrarId = registrarId == null ? null : registrarId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_couple.delflg
     *
     * @return the value of tbl_couple.delflg
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public Boolean getDelflg() {
        return delflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_couple.delflg
     *
     * @param delflg the value for tbl_couple.delflg
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public void setDelflg(Boolean delflg) {
        this.delflg = delflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_couple.create_dt
     *
     * @return the value of tbl_couple.create_dt
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public String getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_couple.create_dt
     *
     * @param createDt the value for tbl_couple.create_dt
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public void setCreateDt(String createDt) {
        this.createDt = createDt == null ? null : createDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_couple.update_dt
     *
     * @return the value of tbl_couple.update_dt
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_couple.update_dt
     *
     * @param updateDt the value for tbl_couple.update_dt
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt == null ? null : updateDt.trim();
    }
}