package com.bloodnet.api.model;

public class TblProfile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.profile_id
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String profileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.sex
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.family_name
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String familyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.first_name
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.family_name_eng
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String familyNameEng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.first_name_eng
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String firstNameEng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.image_file_no
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String imageFileNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.birthdate
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String birthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.death_date
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String deathDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.ID_number
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String idNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.country
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.dynasty
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String dynasty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.email
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.work_div
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String workDiv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.province_code
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String provinceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.city_code
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String cityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.address1
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String address1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.address2
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String address2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.delflg
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private Boolean delflg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.create_app
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String createApp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.create_user
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.create_dt
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.update_app
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String updateApp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.update_user
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.update_dt
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    private String updateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.profile_id
     *
     * @return the value of tbl_profile.profile_id
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.profile_id
     *
     * @param profileId the value for tbl_profile.profile_id
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setProfileId(String profileId) {
        this.profileId = profileId == null ? null : profileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.sex
     *
     * @return the value of tbl_profile.sex
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.sex
     *
     * @param sex the value for tbl_profile.sex
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.family_name
     *
     * @return the value of tbl_profile.family_name
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.family_name
     *
     * @param familyName the value for tbl_profile.family_name
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setFamilyName(String familyName) {
        this.familyName = familyName == null ? null : familyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.first_name
     *
     * @return the value of tbl_profile.first_name
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.first_name
     *
     * @param firstName the value for tbl_profile.first_name
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.family_name_eng
     *
     * @return the value of tbl_profile.family_name_eng
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getFamilyNameEng() {
        return familyNameEng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.family_name_eng
     *
     * @param familyNameEng the value for tbl_profile.family_name_eng
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setFamilyNameEng(String familyNameEng) {
        this.familyNameEng = familyNameEng == null ? null : familyNameEng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.first_name_eng
     *
     * @return the value of tbl_profile.first_name_eng
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getFirstNameEng() {
        return firstNameEng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.first_name_eng
     *
     * @param firstNameEng the value for tbl_profile.first_name_eng
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setFirstNameEng(String firstNameEng) {
        this.firstNameEng = firstNameEng == null ? null : firstNameEng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.image_file_no
     *
     * @return the value of tbl_profile.image_file_no
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getImageFileNo() {
        return imageFileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.image_file_no
     *
     * @param imageFileNo the value for tbl_profile.image_file_no
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setImageFileNo(String imageFileNo) {
        this.imageFileNo = imageFileNo == null ? null : imageFileNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.birthdate
     *
     * @return the value of tbl_profile.birthdate
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.birthdate
     *
     * @param birthdate the value for tbl_profile.birthdate
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate == null ? null : birthdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.death_date
     *
     * @return the value of tbl_profile.death_date
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getDeathDate() {
        return deathDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.death_date
     *
     * @param deathDate the value for tbl_profile.death_date
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setDeathDate(String deathDate) {
        this.deathDate = deathDate == null ? null : deathDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.ID_number
     *
     * @return the value of tbl_profile.ID_number
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.ID_number
     *
     * @param idNumber the value for tbl_profile.ID_number
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.country
     *
     * @return the value of tbl_profile.country
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.country
     *
     * @param country the value for tbl_profile.country
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.dynasty
     *
     * @return the value of tbl_profile.dynasty
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getDynasty() {
        return dynasty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.dynasty
     *
     * @param dynasty the value for tbl_profile.dynasty
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setDynasty(String dynasty) {
        this.dynasty = dynasty == null ? null : dynasty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.email
     *
     * @return the value of tbl_profile.email
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.email
     *
     * @param email the value for tbl_profile.email
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.work_div
     *
     * @return the value of tbl_profile.work_div
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getWorkDiv() {
        return workDiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.work_div
     *
     * @param workDiv the value for tbl_profile.work_div
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setWorkDiv(String workDiv) {
        this.workDiv = workDiv == null ? null : workDiv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.province_code
     *
     * @return the value of tbl_profile.province_code
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.province_code
     *
     * @param provinceCode the value for tbl_profile.province_code
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.city_code
     *
     * @return the value of tbl_profile.city_code
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.city_code
     *
     * @param cityCode the value for tbl_profile.city_code
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.address1
     *
     * @return the value of tbl_profile.address1
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.address1
     *
     * @param address1 the value for tbl_profile.address1
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setAddress1(String address1) {
        this.address1 = address1 == null ? null : address1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.address2
     *
     * @return the value of tbl_profile.address2
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.address2
     *
     * @param address2 the value for tbl_profile.address2
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setAddress2(String address2) {
        this.address2 = address2 == null ? null : address2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.delflg
     *
     * @return the value of tbl_profile.delflg
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public Boolean getDelflg() {
        return delflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.delflg
     *
     * @param delflg the value for tbl_profile.delflg
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setDelflg(Boolean delflg) {
        this.delflg = delflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.create_app
     *
     * @return the value of tbl_profile.create_app
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getCreateApp() {
        return createApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.create_app
     *
     * @param createApp the value for tbl_profile.create_app
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setCreateApp(String createApp) {
        this.createApp = createApp == null ? null : createApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.create_user
     *
     * @return the value of tbl_profile.create_user
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.create_user
     *
     * @param createUser the value for tbl_profile.create_user
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.create_dt
     *
     * @return the value of tbl_profile.create_dt
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.create_dt
     *
     * @param createDt the value for tbl_profile.create_dt
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setCreateDt(String createDt) {
        this.createDt = createDt == null ? null : createDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.update_app
     *
     * @return the value of tbl_profile.update_app
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getUpdateApp() {
        return updateApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.update_app
     *
     * @param updateApp the value for tbl_profile.update_app
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setUpdateApp(String updateApp) {
        this.updateApp = updateApp == null ? null : updateApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.update_user
     *
     * @return the value of tbl_profile.update_user
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.update_user
     *
     * @param updateUser the value for tbl_profile.update_user
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.update_dt
     *
     * @return the value of tbl_profile.update_dt
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.update_dt
     *
     * @param updateDt the value for tbl_profile.update_dt
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt == null ? null : updateDt.trim();
    }
}