package com.bloodnet.api.model;

public class TblProfile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.profile_id
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    private String profileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.sex
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.family_name
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    private String familyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.first_name
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.birthyear
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    private String birthyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.ID_number
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    private String idNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.email
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.phone_no
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    private String phoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.delflg
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    private Boolean delflg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.create_dt
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    private String createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_profile.update_dt
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    private String updateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.profile_id
     *
     * @return the value of tbl_profile.profile_id
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public String getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.profile_id
     *
     * @param profileId the value for tbl_profile.profile_id
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public void setProfileId(String profileId) {
        this.profileId = profileId == null ? null : profileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.sex
     *
     * @return the value of tbl_profile.sex
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.sex
     *
     * @param sex the value for tbl_profile.sex
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.family_name
     *
     * @return the value of tbl_profile.family_name
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.family_name
     *
     * @param familyName the value for tbl_profile.family_name
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public void setFamilyName(String familyName) {
        this.familyName = familyName == null ? null : familyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.first_name
     *
     * @return the value of tbl_profile.first_name
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.first_name
     *
     * @param firstName the value for tbl_profile.first_name
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.birthyear
     *
     * @return the value of tbl_profile.birthyear
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public String getBirthyear() {
        return birthyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.birthyear
     *
     * @param birthyear the value for tbl_profile.birthyear
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public void setBirthyear(String birthyear) {
        this.birthyear = birthyear == null ? null : birthyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.ID_number
     *
     * @return the value of tbl_profile.ID_number
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.ID_number
     *
     * @param idNumber the value for tbl_profile.ID_number
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.email
     *
     * @return the value of tbl_profile.email
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.email
     *
     * @param email the value for tbl_profile.email
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.phone_no
     *
     * @return the value of tbl_profile.phone_no
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.phone_no
     *
     * @param phoneNo the value for tbl_profile.phone_no
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.delflg
     *
     * @return the value of tbl_profile.delflg
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public Boolean getDelflg() {
        return delflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.delflg
     *
     * @param delflg the value for tbl_profile.delflg
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public void setDelflg(Boolean delflg) {
        this.delflg = delflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.create_dt
     *
     * @return the value of tbl_profile.create_dt
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public String getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.create_dt
     *
     * @param createDt the value for tbl_profile.create_dt
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public void setCreateDt(String createDt) {
        this.createDt = createDt == null ? null : createDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_profile.update_dt
     *
     * @return the value of tbl_profile.update_dt
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_profile.update_dt
     *
     * @param updateDt the value for tbl_profile.update_dt
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt == null ? null : updateDt.trim();
    }
}