package com.bloodnet.api.model;

public class TblRelationStepmotherSon {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_relation_stepmother_son.stepmother_profile_id
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private String stepmotherProfileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_relation_stepmother_son.stepson_profile_id
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private String stepsonProfileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_relation_stepmother_son.registrar_id
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private String registrarId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_relation_stepmother_son.delflg
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private Boolean delflg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_relation_stepmother_son.create_app
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private String createApp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_relation_stepmother_son.create_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_relation_stepmother_son.create_dt
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private String createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_relation_stepmother_son.update_app
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private String updateApp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_relation_stepmother_son.update_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_relation_stepmother_son.update_dt
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private String updateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_relation_stepmother_son.stepmother_profile_id
     *
     * @return the value of tbl_relation_stepmother_son.stepmother_profile_id
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getStepmotherProfileId() {
        return stepmotherProfileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_relation_stepmother_son.stepmother_profile_id
     *
     * @param stepmotherProfileId the value for tbl_relation_stepmother_son.stepmother_profile_id
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setStepmotherProfileId(String stepmotherProfileId) {
        this.stepmotherProfileId = stepmotherProfileId == null ? null : stepmotherProfileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_relation_stepmother_son.stepson_profile_id
     *
     * @return the value of tbl_relation_stepmother_son.stepson_profile_id
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getStepsonProfileId() {
        return stepsonProfileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_relation_stepmother_son.stepson_profile_id
     *
     * @param stepsonProfileId the value for tbl_relation_stepmother_son.stepson_profile_id
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setStepsonProfileId(String stepsonProfileId) {
        this.stepsonProfileId = stepsonProfileId == null ? null : stepsonProfileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_relation_stepmother_son.registrar_id
     *
     * @return the value of tbl_relation_stepmother_son.registrar_id
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getRegistrarId() {
        return registrarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_relation_stepmother_son.registrar_id
     *
     * @param registrarId the value for tbl_relation_stepmother_son.registrar_id
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setRegistrarId(String registrarId) {
        this.registrarId = registrarId == null ? null : registrarId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_relation_stepmother_son.delflg
     *
     * @return the value of tbl_relation_stepmother_son.delflg
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public Boolean getDelflg() {
        return delflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_relation_stepmother_son.delflg
     *
     * @param delflg the value for tbl_relation_stepmother_son.delflg
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setDelflg(Boolean delflg) {
        this.delflg = delflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_relation_stepmother_son.create_app
     *
     * @return the value of tbl_relation_stepmother_son.create_app
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getCreateApp() {
        return createApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_relation_stepmother_son.create_app
     *
     * @param createApp the value for tbl_relation_stepmother_son.create_app
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setCreateApp(String createApp) {
        this.createApp = createApp == null ? null : createApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_relation_stepmother_son.create_user
     *
     * @return the value of tbl_relation_stepmother_son.create_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_relation_stepmother_son.create_user
     *
     * @param createUser the value for tbl_relation_stepmother_son.create_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_relation_stepmother_son.create_dt
     *
     * @return the value of tbl_relation_stepmother_son.create_dt
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_relation_stepmother_son.create_dt
     *
     * @param createDt the value for tbl_relation_stepmother_son.create_dt
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setCreateDt(String createDt) {
        this.createDt = createDt == null ? null : createDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_relation_stepmother_son.update_app
     *
     * @return the value of tbl_relation_stepmother_son.update_app
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getUpdateApp() {
        return updateApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_relation_stepmother_son.update_app
     *
     * @param updateApp the value for tbl_relation_stepmother_son.update_app
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setUpdateApp(String updateApp) {
        this.updateApp = updateApp == null ? null : updateApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_relation_stepmother_son.update_user
     *
     * @return the value of tbl_relation_stepmother_son.update_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_relation_stepmother_son.update_user
     *
     * @param updateUser the value for tbl_relation_stepmother_son.update_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_relation_stepmother_son.update_dt
     *
     * @return the value of tbl_relation_stepmother_son.update_dt
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_relation_stepmother_son.update_dt
     *
     * @param updateDt the value for tbl_relation_stepmother_son.update_dt
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt == null ? null : updateDt.trim();
    }
}