package com.bloodnet.api.model;

public class TblRelationMotherDaughter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_relation_mother_daughter.mother_profile_id
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    private String motherProfileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_relation_mother_daughter.daughter_profile_id
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    private String daughterProfileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_relation_mother_daughter.registrar_id
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    private String registrarId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_relation_mother_daughter.delflg
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    private Boolean delflg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_relation_mother_daughter.create_app
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    private String createApp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_relation_mother_daughter.create_user
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_relation_mother_daughter.create_dt
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    private String createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_relation_mother_daughter.update_app
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    private String updateApp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_relation_mother_daughter.update_user
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_relation_mother_daughter.update_dt
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    private String updateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_relation_mother_daughter.mother_profile_id
     *
     * @return the value of tbl_relation_mother_daughter.mother_profile_id
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public String getMotherProfileId() {
        return motherProfileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_relation_mother_daughter.mother_profile_id
     *
     * @param motherProfileId the value for tbl_relation_mother_daughter.mother_profile_id
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public void setMotherProfileId(String motherProfileId) {
        this.motherProfileId = motherProfileId == null ? null : motherProfileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_relation_mother_daughter.daughter_profile_id
     *
     * @return the value of tbl_relation_mother_daughter.daughter_profile_id
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public String getDaughterProfileId() {
        return daughterProfileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_relation_mother_daughter.daughter_profile_id
     *
     * @param daughterProfileId the value for tbl_relation_mother_daughter.daughter_profile_id
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public void setDaughterProfileId(String daughterProfileId) {
        this.daughterProfileId = daughterProfileId == null ? null : daughterProfileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_relation_mother_daughter.registrar_id
     *
     * @return the value of tbl_relation_mother_daughter.registrar_id
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public String getRegistrarId() {
        return registrarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_relation_mother_daughter.registrar_id
     *
     * @param registrarId the value for tbl_relation_mother_daughter.registrar_id
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public void setRegistrarId(String registrarId) {
        this.registrarId = registrarId == null ? null : registrarId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_relation_mother_daughter.delflg
     *
     * @return the value of tbl_relation_mother_daughter.delflg
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public Boolean getDelflg() {
        return delflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_relation_mother_daughter.delflg
     *
     * @param delflg the value for tbl_relation_mother_daughter.delflg
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public void setDelflg(Boolean delflg) {
        this.delflg = delflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_relation_mother_daughter.create_app
     *
     * @return the value of tbl_relation_mother_daughter.create_app
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public String getCreateApp() {
        return createApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_relation_mother_daughter.create_app
     *
     * @param createApp the value for tbl_relation_mother_daughter.create_app
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public void setCreateApp(String createApp) {
        this.createApp = createApp == null ? null : createApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_relation_mother_daughter.create_user
     *
     * @return the value of tbl_relation_mother_daughter.create_user
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_relation_mother_daughter.create_user
     *
     * @param createUser the value for tbl_relation_mother_daughter.create_user
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_relation_mother_daughter.create_dt
     *
     * @return the value of tbl_relation_mother_daughter.create_dt
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public String getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_relation_mother_daughter.create_dt
     *
     * @param createDt the value for tbl_relation_mother_daughter.create_dt
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public void setCreateDt(String createDt) {
        this.createDt = createDt == null ? null : createDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_relation_mother_daughter.update_app
     *
     * @return the value of tbl_relation_mother_daughter.update_app
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public String getUpdateApp() {
        return updateApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_relation_mother_daughter.update_app
     *
     * @param updateApp the value for tbl_relation_mother_daughter.update_app
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public void setUpdateApp(String updateApp) {
        this.updateApp = updateApp == null ? null : updateApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_relation_mother_daughter.update_user
     *
     * @return the value of tbl_relation_mother_daughter.update_user
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_relation_mother_daughter.update_user
     *
     * @param updateUser the value for tbl_relation_mother_daughter.update_user
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_relation_mother_daughter.update_dt
     *
     * @return the value of tbl_relation_mother_daughter.update_dt
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_relation_mother_daughter.update_dt
     *
     * @param updateDt the value for tbl_relation_mother_daughter.update_dt
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt == null ? null : updateDt.trim();
    }
}