package com.bloodnet.api.model;

public class TblUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.user_id
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.profile_id
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private String profileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.password
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.last_password_change_ymd
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private String lastPasswordChangeYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.login_failed_cnt
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private Integer loginFailedCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.secondary_email
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private String secondaryEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.account_status
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private String accountStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.lock_flg
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private Boolean lockFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.salt
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.delflg
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private Boolean delflg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.create_app
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private String createApp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.create_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.create_dt
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private String createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.update_app
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private String updateApp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.update_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.update_dt
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    private String updateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.user_id
     *
     * @return the value of tbl_user.user_id
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.user_id
     *
     * @param userId the value for tbl_user.user_id
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.profile_id
     *
     * @return the value of tbl_user.profile_id
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.profile_id
     *
     * @param profileId the value for tbl_user.profile_id
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setProfileId(String profileId) {
        this.profileId = profileId == null ? null : profileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.password
     *
     * @return the value of tbl_user.password
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.password
     *
     * @param password the value for tbl_user.password
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.last_password_change_ymd
     *
     * @return the value of tbl_user.last_password_change_ymd
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getLastPasswordChangeYmd() {
        return lastPasswordChangeYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.last_password_change_ymd
     *
     * @param lastPasswordChangeYmd the value for tbl_user.last_password_change_ymd
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setLastPasswordChangeYmd(String lastPasswordChangeYmd) {
        this.lastPasswordChangeYmd = lastPasswordChangeYmd == null ? null : lastPasswordChangeYmd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.login_failed_cnt
     *
     * @return the value of tbl_user.login_failed_cnt
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public Integer getLoginFailedCnt() {
        return loginFailedCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.login_failed_cnt
     *
     * @param loginFailedCnt the value for tbl_user.login_failed_cnt
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setLoginFailedCnt(Integer loginFailedCnt) {
        this.loginFailedCnt = loginFailedCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.secondary_email
     *
     * @return the value of tbl_user.secondary_email
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getSecondaryEmail() {
        return secondaryEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.secondary_email
     *
     * @param secondaryEmail the value for tbl_user.secondary_email
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setSecondaryEmail(String secondaryEmail) {
        this.secondaryEmail = secondaryEmail == null ? null : secondaryEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.account_status
     *
     * @return the value of tbl_user.account_status
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getAccountStatus() {
        return accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.account_status
     *
     * @param accountStatus the value for tbl_user.account_status
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setAccountStatus(String accountStatus) {
        this.accountStatus = accountStatus == null ? null : accountStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.lock_flg
     *
     * @return the value of tbl_user.lock_flg
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public Boolean getLockFlg() {
        return lockFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.lock_flg
     *
     * @param lockFlg the value for tbl_user.lock_flg
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setLockFlg(Boolean lockFlg) {
        this.lockFlg = lockFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.salt
     *
     * @return the value of tbl_user.salt
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.salt
     *
     * @param salt the value for tbl_user.salt
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.delflg
     *
     * @return the value of tbl_user.delflg
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public Boolean getDelflg() {
        return delflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.delflg
     *
     * @param delflg the value for tbl_user.delflg
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setDelflg(Boolean delflg) {
        this.delflg = delflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.create_app
     *
     * @return the value of tbl_user.create_app
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getCreateApp() {
        return createApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.create_app
     *
     * @param createApp the value for tbl_user.create_app
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setCreateApp(String createApp) {
        this.createApp = createApp == null ? null : createApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.create_user
     *
     * @return the value of tbl_user.create_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.create_user
     *
     * @param createUser the value for tbl_user.create_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.create_dt
     *
     * @return the value of tbl_user.create_dt
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.create_dt
     *
     * @param createDt the value for tbl_user.create_dt
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setCreateDt(String createDt) {
        this.createDt = createDt == null ? null : createDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.update_app
     *
     * @return the value of tbl_user.update_app
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getUpdateApp() {
        return updateApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.update_app
     *
     * @param updateApp the value for tbl_user.update_app
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setUpdateApp(String updateApp) {
        this.updateApp = updateApp == null ? null : updateApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.update_user
     *
     * @return the value of tbl_user.update_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.update_user
     *
     * @param updateUser the value for tbl_user.update_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.update_dt
     *
     * @return the value of tbl_user.update_dt
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.update_dt
     *
     * @param updateDt the value for tbl_user.update_dt
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt == null ? null : updateDt.trim();
    }
}