package com.bloodnet.api.model;

import java.util.ArrayList;
import java.util.List;

public class TblUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public TblUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andProfileIdIsNull() {
            addCriterion("profile_id is null");
            return (Criteria) this;
        }

        public Criteria andProfileIdIsNotNull() {
            addCriterion("profile_id is not null");
            return (Criteria) this;
        }

        public Criteria andProfileIdEqualTo(String value) {
            addCriterion("profile_id =", value, "profileId");
            return (Criteria) this;
        }

        public Criteria andProfileIdNotEqualTo(String value) {
            addCriterion("profile_id <>", value, "profileId");
            return (Criteria) this;
        }

        public Criteria andProfileIdGreaterThan(String value) {
            addCriterion("profile_id >", value, "profileId");
            return (Criteria) this;
        }

        public Criteria andProfileIdGreaterThanOrEqualTo(String value) {
            addCriterion("profile_id >=", value, "profileId");
            return (Criteria) this;
        }

        public Criteria andProfileIdLessThan(String value) {
            addCriterion("profile_id <", value, "profileId");
            return (Criteria) this;
        }

        public Criteria andProfileIdLessThanOrEqualTo(String value) {
            addCriterion("profile_id <=", value, "profileId");
            return (Criteria) this;
        }

        public Criteria andProfileIdLike(String value) {
            addCriterion("profile_id like", value, "profileId");
            return (Criteria) this;
        }

        public Criteria andProfileIdNotLike(String value) {
            addCriterion("profile_id not like", value, "profileId");
            return (Criteria) this;
        }

        public Criteria andProfileIdIn(List<String> values) {
            addCriterion("profile_id in", values, "profileId");
            return (Criteria) this;
        }

        public Criteria andProfileIdNotIn(List<String> values) {
            addCriterion("profile_id not in", values, "profileId");
            return (Criteria) this;
        }

        public Criteria andProfileIdBetween(String value1, String value2) {
            addCriterion("profile_id between", value1, value2, "profileId");
            return (Criteria) this;
        }

        public Criteria andProfileIdNotBetween(String value1, String value2) {
            addCriterion("profile_id not between", value1, value2, "profileId");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeYmdIsNull() {
            addCriterion("last_password_change_ymd is null");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeYmdIsNotNull() {
            addCriterion("last_password_change_ymd is not null");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeYmdEqualTo(String value) {
            addCriterion("last_password_change_ymd =", value, "lastPasswordChangeYmd");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeYmdNotEqualTo(String value) {
            addCriterion("last_password_change_ymd <>", value, "lastPasswordChangeYmd");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeYmdGreaterThan(String value) {
            addCriterion("last_password_change_ymd >", value, "lastPasswordChangeYmd");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeYmdGreaterThanOrEqualTo(String value) {
            addCriterion("last_password_change_ymd >=", value, "lastPasswordChangeYmd");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeYmdLessThan(String value) {
            addCriterion("last_password_change_ymd <", value, "lastPasswordChangeYmd");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeYmdLessThanOrEqualTo(String value) {
            addCriterion("last_password_change_ymd <=", value, "lastPasswordChangeYmd");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeYmdLike(String value) {
            addCriterion("last_password_change_ymd like", value, "lastPasswordChangeYmd");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeYmdNotLike(String value) {
            addCriterion("last_password_change_ymd not like", value, "lastPasswordChangeYmd");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeYmdIn(List<String> values) {
            addCriterion("last_password_change_ymd in", values, "lastPasswordChangeYmd");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeYmdNotIn(List<String> values) {
            addCriterion("last_password_change_ymd not in", values, "lastPasswordChangeYmd");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeYmdBetween(String value1, String value2) {
            addCriterion("last_password_change_ymd between", value1, value2, "lastPasswordChangeYmd");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeYmdNotBetween(String value1, String value2) {
            addCriterion("last_password_change_ymd not between", value1, value2, "lastPasswordChangeYmd");
            return (Criteria) this;
        }

        public Criteria andLoginFailedCntIsNull() {
            addCriterion("login_failed_cnt is null");
            return (Criteria) this;
        }

        public Criteria andLoginFailedCntIsNotNull() {
            addCriterion("login_failed_cnt is not null");
            return (Criteria) this;
        }

        public Criteria andLoginFailedCntEqualTo(Integer value) {
            addCriterion("login_failed_cnt =", value, "loginFailedCnt");
            return (Criteria) this;
        }

        public Criteria andLoginFailedCntNotEqualTo(Integer value) {
            addCriterion("login_failed_cnt <>", value, "loginFailedCnt");
            return (Criteria) this;
        }

        public Criteria andLoginFailedCntGreaterThan(Integer value) {
            addCriterion("login_failed_cnt >", value, "loginFailedCnt");
            return (Criteria) this;
        }

        public Criteria andLoginFailedCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("login_failed_cnt >=", value, "loginFailedCnt");
            return (Criteria) this;
        }

        public Criteria andLoginFailedCntLessThan(Integer value) {
            addCriterion("login_failed_cnt <", value, "loginFailedCnt");
            return (Criteria) this;
        }

        public Criteria andLoginFailedCntLessThanOrEqualTo(Integer value) {
            addCriterion("login_failed_cnt <=", value, "loginFailedCnt");
            return (Criteria) this;
        }

        public Criteria andLoginFailedCntIn(List<Integer> values) {
            addCriterion("login_failed_cnt in", values, "loginFailedCnt");
            return (Criteria) this;
        }

        public Criteria andLoginFailedCntNotIn(List<Integer> values) {
            addCriterion("login_failed_cnt not in", values, "loginFailedCnt");
            return (Criteria) this;
        }

        public Criteria andLoginFailedCntBetween(Integer value1, Integer value2) {
            addCriterion("login_failed_cnt between", value1, value2, "loginFailedCnt");
            return (Criteria) this;
        }

        public Criteria andLoginFailedCntNotBetween(Integer value1, Integer value2) {
            addCriterion("login_failed_cnt not between", value1, value2, "loginFailedCnt");
            return (Criteria) this;
        }

        public Criteria andSecondaryEmailIsNull() {
            addCriterion("secondary_email is null");
            return (Criteria) this;
        }

        public Criteria andSecondaryEmailIsNotNull() {
            addCriterion("secondary_email is not null");
            return (Criteria) this;
        }

        public Criteria andSecondaryEmailEqualTo(String value) {
            addCriterion("secondary_email =", value, "secondaryEmail");
            return (Criteria) this;
        }

        public Criteria andSecondaryEmailNotEqualTo(String value) {
            addCriterion("secondary_email <>", value, "secondaryEmail");
            return (Criteria) this;
        }

        public Criteria andSecondaryEmailGreaterThan(String value) {
            addCriterion("secondary_email >", value, "secondaryEmail");
            return (Criteria) this;
        }

        public Criteria andSecondaryEmailGreaterThanOrEqualTo(String value) {
            addCriterion("secondary_email >=", value, "secondaryEmail");
            return (Criteria) this;
        }

        public Criteria andSecondaryEmailLessThan(String value) {
            addCriterion("secondary_email <", value, "secondaryEmail");
            return (Criteria) this;
        }

        public Criteria andSecondaryEmailLessThanOrEqualTo(String value) {
            addCriterion("secondary_email <=", value, "secondaryEmail");
            return (Criteria) this;
        }

        public Criteria andSecondaryEmailLike(String value) {
            addCriterion("secondary_email like", value, "secondaryEmail");
            return (Criteria) this;
        }

        public Criteria andSecondaryEmailNotLike(String value) {
            addCriterion("secondary_email not like", value, "secondaryEmail");
            return (Criteria) this;
        }

        public Criteria andSecondaryEmailIn(List<String> values) {
            addCriterion("secondary_email in", values, "secondaryEmail");
            return (Criteria) this;
        }

        public Criteria andSecondaryEmailNotIn(List<String> values) {
            addCriterion("secondary_email not in", values, "secondaryEmail");
            return (Criteria) this;
        }

        public Criteria andSecondaryEmailBetween(String value1, String value2) {
            addCriterion("secondary_email between", value1, value2, "secondaryEmail");
            return (Criteria) this;
        }

        public Criteria andSecondaryEmailNotBetween(String value1, String value2) {
            addCriterion("secondary_email not between", value1, value2, "secondaryEmail");
            return (Criteria) this;
        }

        public Criteria andAccountStatusIsNull() {
            addCriterion("account_status is null");
            return (Criteria) this;
        }

        public Criteria andAccountStatusIsNotNull() {
            addCriterion("account_status is not null");
            return (Criteria) this;
        }

        public Criteria andAccountStatusEqualTo(String value) {
            addCriterion("account_status =", value, "accountStatus");
            return (Criteria) this;
        }

        public Criteria andAccountStatusNotEqualTo(String value) {
            addCriterion("account_status <>", value, "accountStatus");
            return (Criteria) this;
        }

        public Criteria andAccountStatusGreaterThan(String value) {
            addCriterion("account_status >", value, "accountStatus");
            return (Criteria) this;
        }

        public Criteria andAccountStatusGreaterThanOrEqualTo(String value) {
            addCriterion("account_status >=", value, "accountStatus");
            return (Criteria) this;
        }

        public Criteria andAccountStatusLessThan(String value) {
            addCriterion("account_status <", value, "accountStatus");
            return (Criteria) this;
        }

        public Criteria andAccountStatusLessThanOrEqualTo(String value) {
            addCriterion("account_status <=", value, "accountStatus");
            return (Criteria) this;
        }

        public Criteria andAccountStatusLike(String value) {
            addCriterion("account_status like", value, "accountStatus");
            return (Criteria) this;
        }

        public Criteria andAccountStatusNotLike(String value) {
            addCriterion("account_status not like", value, "accountStatus");
            return (Criteria) this;
        }

        public Criteria andAccountStatusIn(List<String> values) {
            addCriterion("account_status in", values, "accountStatus");
            return (Criteria) this;
        }

        public Criteria andAccountStatusNotIn(List<String> values) {
            addCriterion("account_status not in", values, "accountStatus");
            return (Criteria) this;
        }

        public Criteria andAccountStatusBetween(String value1, String value2) {
            addCriterion("account_status between", value1, value2, "accountStatus");
            return (Criteria) this;
        }

        public Criteria andAccountStatusNotBetween(String value1, String value2) {
            addCriterion("account_status not between", value1, value2, "accountStatus");
            return (Criteria) this;
        }

        public Criteria andLockFlgIsNull() {
            addCriterion("lock_flg is null");
            return (Criteria) this;
        }

        public Criteria andLockFlgIsNotNull() {
            addCriterion("lock_flg is not null");
            return (Criteria) this;
        }

        public Criteria andLockFlgEqualTo(Boolean value) {
            addCriterion("lock_flg =", value, "lockFlg");
            return (Criteria) this;
        }

        public Criteria andLockFlgNotEqualTo(Boolean value) {
            addCriterion("lock_flg <>", value, "lockFlg");
            return (Criteria) this;
        }

        public Criteria andLockFlgGreaterThan(Boolean value) {
            addCriterion("lock_flg >", value, "lockFlg");
            return (Criteria) this;
        }

        public Criteria andLockFlgGreaterThanOrEqualTo(Boolean value) {
            addCriterion("lock_flg >=", value, "lockFlg");
            return (Criteria) this;
        }

        public Criteria andLockFlgLessThan(Boolean value) {
            addCriterion("lock_flg <", value, "lockFlg");
            return (Criteria) this;
        }

        public Criteria andLockFlgLessThanOrEqualTo(Boolean value) {
            addCriterion("lock_flg <=", value, "lockFlg");
            return (Criteria) this;
        }

        public Criteria andLockFlgIn(List<Boolean> values) {
            addCriterion("lock_flg in", values, "lockFlg");
            return (Criteria) this;
        }

        public Criteria andLockFlgNotIn(List<Boolean> values) {
            addCriterion("lock_flg not in", values, "lockFlg");
            return (Criteria) this;
        }

        public Criteria andLockFlgBetween(Boolean value1, Boolean value2) {
            addCriterion("lock_flg between", value1, value2, "lockFlg");
            return (Criteria) this;
        }

        public Criteria andLockFlgNotBetween(Boolean value1, Boolean value2) {
            addCriterion("lock_flg not between", value1, value2, "lockFlg");
            return (Criteria) this;
        }

        public Criteria andSaltIsNull() {
            addCriterion("salt is null");
            return (Criteria) this;
        }

        public Criteria andSaltIsNotNull() {
            addCriterion("salt is not null");
            return (Criteria) this;
        }

        public Criteria andSaltEqualTo(String value) {
            addCriterion("salt =", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotEqualTo(String value) {
            addCriterion("salt <>", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThan(String value) {
            addCriterion("salt >", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThanOrEqualTo(String value) {
            addCriterion("salt >=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThan(String value) {
            addCriterion("salt <", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThanOrEqualTo(String value) {
            addCriterion("salt <=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLike(String value) {
            addCriterion("salt like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotLike(String value) {
            addCriterion("salt not like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltIn(List<String> values) {
            addCriterion("salt in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotIn(List<String> values) {
            addCriterion("salt not in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltBetween(String value1, String value2) {
            addCriterion("salt between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotBetween(String value1, String value2) {
            addCriterion("salt not between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andDelflgIsNull() {
            addCriterion("delflg is null");
            return (Criteria) this;
        }

        public Criteria andDelflgIsNotNull() {
            addCriterion("delflg is not null");
            return (Criteria) this;
        }

        public Criteria andDelflgEqualTo(Boolean value) {
            addCriterion("delflg =", value, "delflg");
            return (Criteria) this;
        }

        public Criteria andDelflgNotEqualTo(Boolean value) {
            addCriterion("delflg <>", value, "delflg");
            return (Criteria) this;
        }

        public Criteria andDelflgGreaterThan(Boolean value) {
            addCriterion("delflg >", value, "delflg");
            return (Criteria) this;
        }

        public Criteria andDelflgGreaterThanOrEqualTo(Boolean value) {
            addCriterion("delflg >=", value, "delflg");
            return (Criteria) this;
        }

        public Criteria andDelflgLessThan(Boolean value) {
            addCriterion("delflg <", value, "delflg");
            return (Criteria) this;
        }

        public Criteria andDelflgLessThanOrEqualTo(Boolean value) {
            addCriterion("delflg <=", value, "delflg");
            return (Criteria) this;
        }

        public Criteria andDelflgIn(List<Boolean> values) {
            addCriterion("delflg in", values, "delflg");
            return (Criteria) this;
        }

        public Criteria andDelflgNotIn(List<Boolean> values) {
            addCriterion("delflg not in", values, "delflg");
            return (Criteria) this;
        }

        public Criteria andDelflgBetween(Boolean value1, Boolean value2) {
            addCriterion("delflg between", value1, value2, "delflg");
            return (Criteria) this;
        }

        public Criteria andDelflgNotBetween(Boolean value1, Boolean value2) {
            addCriterion("delflg not between", value1, value2, "delflg");
            return (Criteria) this;
        }

        public Criteria andCreateAppIsNull() {
            addCriterion("create_app is null");
            return (Criteria) this;
        }

        public Criteria andCreateAppIsNotNull() {
            addCriterion("create_app is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAppEqualTo(String value) {
            addCriterion("create_app =", value, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateAppNotEqualTo(String value) {
            addCriterion("create_app <>", value, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateAppGreaterThan(String value) {
            addCriterion("create_app >", value, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateAppGreaterThanOrEqualTo(String value) {
            addCriterion("create_app >=", value, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateAppLessThan(String value) {
            addCriterion("create_app <", value, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateAppLessThanOrEqualTo(String value) {
            addCriterion("create_app <=", value, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateAppLike(String value) {
            addCriterion("create_app like", value, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateAppNotLike(String value) {
            addCriterion("create_app not like", value, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateAppIn(List<String> values) {
            addCriterion("create_app in", values, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateAppNotIn(List<String> values) {
            addCriterion("create_app not in", values, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateAppBetween(String value1, String value2) {
            addCriterion("create_app between", value1, value2, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateAppNotBetween(String value1, String value2) {
            addCriterion("create_app not between", value1, value2, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateDtIsNull() {
            addCriterion("create_dt is null");
            return (Criteria) this;
        }

        public Criteria andCreateDtIsNotNull() {
            addCriterion("create_dt is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDtEqualTo(String value) {
            addCriterion("create_dt =", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtNotEqualTo(String value) {
            addCriterion("create_dt <>", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtGreaterThan(String value) {
            addCriterion("create_dt >", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtGreaterThanOrEqualTo(String value) {
            addCriterion("create_dt >=", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtLessThan(String value) {
            addCriterion("create_dt <", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtLessThanOrEqualTo(String value) {
            addCriterion("create_dt <=", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtLike(String value) {
            addCriterion("create_dt like", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtNotLike(String value) {
            addCriterion("create_dt not like", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtIn(List<String> values) {
            addCriterion("create_dt in", values, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtNotIn(List<String> values) {
            addCriterion("create_dt not in", values, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtBetween(String value1, String value2) {
            addCriterion("create_dt between", value1, value2, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtNotBetween(String value1, String value2) {
            addCriterion("create_dt not between", value1, value2, "createDt");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIsNull() {
            addCriterion("update_app is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIsNotNull() {
            addCriterion("update_app is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAppEqualTo(String value) {
            addCriterion("update_app =", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotEqualTo(String value) {
            addCriterion("update_app <>", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppGreaterThan(String value) {
            addCriterion("update_app >", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppGreaterThanOrEqualTo(String value) {
            addCriterion("update_app >=", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLessThan(String value) {
            addCriterion("update_app <", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLessThanOrEqualTo(String value) {
            addCriterion("update_app <=", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLike(String value) {
            addCriterion("update_app like", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotLike(String value) {
            addCriterion("update_app not like", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIn(List<String> values) {
            addCriterion("update_app in", values, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotIn(List<String> values) {
            addCriterion("update_app not in", values, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppBetween(String value1, String value2) {
            addCriterion("update_app between", value1, value2, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotBetween(String value1, String value2) {
            addCriterion("update_app not between", value1, value2, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateDtIsNull() {
            addCriterion("update_dt is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDtIsNotNull() {
            addCriterion("update_dt is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDtEqualTo(String value) {
            addCriterion("update_dt =", value, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtNotEqualTo(String value) {
            addCriterion("update_dt <>", value, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtGreaterThan(String value) {
            addCriterion("update_dt >", value, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtGreaterThanOrEqualTo(String value) {
            addCriterion("update_dt >=", value, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtLessThan(String value) {
            addCriterion("update_dt <", value, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtLessThanOrEqualTo(String value) {
            addCriterion("update_dt <=", value, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtLike(String value) {
            addCriterion("update_dt like", value, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtNotLike(String value) {
            addCriterion("update_dt not like", value, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtIn(List<String> values) {
            addCriterion("update_dt in", values, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtNotIn(List<String> values) {
            addCriterion("update_dt not in", values, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtBetween(String value1, String value2) {
            addCriterion("update_dt between", value1, value2, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtNotBetween(String value1, String value2) {
            addCriterion("update_dt not between", value1, value2, "updateDt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_user
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 07 18:35:46 JST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}