package com.bloodnet.api.mappers;

import com.bloodnet.api.model.TblCouple;
import com.bloodnet.api.model.TblCoupleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblCoupleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_couple
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    int countByExample(TblCoupleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_couple
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    int deleteByExample(TblCoupleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_couple
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    int insert(TblCouple record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_couple
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    int insertSelective(TblCouple record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_couple
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    List<TblCouple> selectByExample(TblCoupleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_couple
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    int updateByExampleSelective(@Param("record") TblCouple record, @Param("example") TblCoupleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_couple
     *
     * @mbggenerated Thu Apr 13 22:20:22 JST 2017
     */
    int updateByExample(@Param("record") TblCouple record, @Param("example") TblCoupleExample example);
}