package com.bloodnet.api.mappers;

import com.bloodnet.api.model.TblRelationFatherDaughter;
import com.bloodnet.api.model.TblRelationFatherDaughterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblRelationFatherDaughterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_father_daughter
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    int countByExample(TblRelationFatherDaughterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_father_daughter
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    int deleteByExample(TblRelationFatherDaughterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_father_daughter
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    int insert(TblRelationFatherDaughter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_father_daughter
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    int insertSelective(TblRelationFatherDaughter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_father_daughter
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    List<TblRelationFatherDaughter> selectByExample(TblRelationFatherDaughterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_father_daughter
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    int updateByExampleSelective(@Param("record") TblRelationFatherDaughter record, @Param("example") TblRelationFatherDaughterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_father_daughter
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    int updateByExample(@Param("record") TblRelationFatherDaughter record, @Param("example") TblRelationFatherDaughterExample example);
}