package com.bloodnet.api.mappers;

import com.bloodnet.api.model.TblRelationStepmotherSon;
import com.bloodnet.api.model.TblRelationStepmotherSonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblRelationStepmotherSonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_stepmother_son
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    int countByExample(TblRelationStepmotherSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_stepmother_son
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    int deleteByExample(TblRelationStepmotherSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_stepmother_son
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    int insert(TblRelationStepmotherSon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_stepmother_son
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    int insertSelective(TblRelationStepmotherSon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_stepmother_son
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    List<TblRelationStepmotherSon> selectByExample(TblRelationStepmotherSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_stepmother_son
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    int updateByExampleSelective(@Param("record") TblRelationStepmotherSon record, @Param("example") TblRelationStepmotherSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_stepmother_son
     *
     * @mbggenerated Tue Apr 04 22:24:13 JST 2017
     */
    int updateByExample(@Param("record") TblRelationStepmotherSon record, @Param("example") TblRelationStepmotherSonExample example);
}