package com.bloodnet.api.mappers;

import com.bloodnet.api.model.TblRelationMotherSon;
import com.bloodnet.api.model.TblRelationMotherSonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblRelationMotherSonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_mother_son
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    int countByExample(TblRelationMotherSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_mother_son
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    int deleteByExample(TblRelationMotherSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_mother_son
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    int insert(TblRelationMotherSon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_mother_son
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    int insertSelective(TblRelationMotherSon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_mother_son
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    List<TblRelationMotherSon> selectByExample(TblRelationMotherSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_mother_son
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    int updateByExampleSelective(@Param("record") TblRelationMotherSon record, @Param("example") TblRelationMotherSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_mother_son
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    int updateByExample(@Param("record") TblRelationMotherSon record, @Param("example") TblRelationMotherSonExample example);
}