package com.bloodnet.api.mappers;

import com.bloodnet.api.model.TblRelationStepmotherDaughter;
import com.bloodnet.api.model.TblRelationStepmotherDaughterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblRelationStepmotherDaughterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_stepmother_daughter
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    int countByExample(TblRelationStepmotherDaughterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_stepmother_daughter
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    int deleteByExample(TblRelationStepmotherDaughterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_stepmother_daughter
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    int insert(TblRelationStepmotherDaughter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_stepmother_daughter
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    int insertSelective(TblRelationStepmotherDaughter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_stepmother_daughter
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    List<TblRelationStepmotherDaughter> selectByExample(TblRelationStepmotherDaughterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_stepmother_daughter
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    int updateByExampleSelective(@Param("record") TblRelationStepmotherDaughter record, @Param("example") TblRelationStepmotherDaughterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_stepmother_daughter
     *
     * @mbggenerated Fri Apr 07 16:00:20 JST 2017
     */
    int updateByExample(@Param("record") TblRelationStepmotherDaughter record, @Param("example") TblRelationStepmotherDaughterExample example);
}