package com.bloodnet.api.mappers;

import com.bloodnet.api.model.TblUser;
import com.bloodnet.api.model.TblUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    int countByExample(TblUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    int deleteByExample(TblUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    int insert(TblUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    int insertSelective(TblUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    List<TblUser> selectByExample(TblUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    int updateByExampleSelective(@Param("record") TblUser record, @Param("example") TblUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Apr 07 18:35:46 JST 2017
     */
    int updateByExample(@Param("record") TblUser record, @Param("example") TblUserExample example);
}